development: &defaults
  site: http://demo.opensourcecurrency.org
  issuer: 1-tom-brown-admin
  currency: hours
  consumer_key: xBoHeeNNFt3LQ7U1tvAb8BVKr32duE6rdWtpCSFD
  consumer_secret: HraYcLT5F5nRll5KF5tw8umdER3EOrsFXIEro67T

test:
  <<: *defaults

production:
  <<: *defaults
